### ISSUE TITLE
Test if the USB-based sensors work well with each other and the computer

### ISSUE THREAD

**Issue by Oluwatoni** [uwrobotics/RobotRacing2018#10]
**Acceptability Criteria**
Check the 3 cameras
Check the Lidar (run the mapping node and note if there any issues and try and fix them if you can, check the rviz visualizations)
Check the Arduino (roslaunch rosserial arduino and check if that runs and check the data is published)
Make sure the udev rules are setup properly and update the documentation surrounding them
Check the udev rules for the camera

**Comment by Oluwatoni** [comment]
@tsugumi0401 has checked all 3 cameras

**Comment by angegu** [comment]
Lidar:
1. power car
2. run mapping node
3. note issues

Arduino:
- launch files -> first thing -> ros lauch ros serial arduino
- names match arduino (port)
- check output -> remote control mode, auto mode, estop
- if publish sensor data (encoder, imu, state)

UDEV:
- if ambitious

**Comment by angegu** [comment]
camera setup:
- when mounted
- check hub

Make setup
