### ISSUE TITLE
Detect the traffic light in an image

### ISSUE THREAD

**Issue by Oluwatoni** [uwrobotics/RobotRacing2018#3]
Use an object detection framework to detect the traffic lights in an image

**Acceptance Criteria**
Inputs
- Forward facing camera stream

Outputs
- Cropped image of the traffic light or no image at all if there is not traffic light

should work on all bags in our [traffic light directory](https://drive.google.com/drive/folders/0B-vTULwBItLDaFR4ampsNU9nQmM?usp=sharing)

YOLO and haar cascades were put forwards as possible options for traffic light detection

**Comment by Oluwatoni** [comment]
Traffic Light bags
https://drive.google.com/drive/folders/0B-vTULwBItLDaFR4ampsNU9nQmM?usp=sharing

**Comment by AdrianMalaran** [comment]
As per discussion, YOLO will be used as the object detection framework for detecting traffic lights in an image.

Sample traffic light detection using YOLO:

[traffic_light_detection.mp4.zip](https://github.com/uwrobotics/RobotRacing2018/files/1949719/traffic_light_detection.mp4.zip)

**Comment by Oluwatoni** [comment]
Deadline: 22nd of May
