### ISSUE TITLE
Create test tracks for the simulated robot

### ISSUE THREAD

**Issue by Oluwatoni** [uwrobotics/RobotRacing2018#8]
Create 3 test tracks for the robot

**Acceptability Criteria**
with the inner line as a yellow line
the outer line as a white line
a magenta line as the end line

The tracks
- a simple oval loop
- a straight track for the drag race
- a more complicated track resembling the competition track
There should be an option to launch the circuit tracks with random obstacles

**Comment by Oluwatoni** [comment]
Drag race courtesy of @JXproject 
![image](https://user-images.githubusercontent.com/10319891/39964493-bc0ca9f4-5653-11e8-847d-3929dc16810d.png)

**Comment by jaku-jaku** [comment]
New Drag Race
<img width="754" alt="dragracetrack" src="https://user-images.githubusercontent.com/15746225/40264705-5eaf01d6-5af8-11e8-8034-939e23352be9.png">

**Comment by jaku-jaku** [comment]
Oval Race Track

<img width="1176" alt="ovalracetrack" src="https://user-images.githubusercontent.com/15746225/40264711-751dd438-5af8-11e8-8b83-b6a02b101961.png">

**Comment by jaku-jaku** [comment]
Oval Race Track Detail shot at start line
<img width="1015" alt="ovalracetrackdetailstartlane" src="https://user-images.githubusercontent.com/15746225/40264712-841954da-5af8-11e8-9ccc-2318ac550e0f.png">

**Comment by jaku-jaku** [comment]
Circuit Race track

![circuitracetracktopview](https://user-images.githubusercontent.com/15746225/40264716-93b9aa5c-5af8-11e8-87e3-810f5ae5650c.png)

**Comment by jaku-jaku** [comment]
Circuit Race Perspectve of the entrance of the shortcut

<img width="1065" alt="circuitracetrackperspectiveshortcut" src="https://user-images.githubusercontent.com/15746225/40264720-9f226e42-5af8-11e8-9351-ce0e0a3ee7ee.png">

**Comment by jaku-jaku** [comment]
Circuit Race Perspective view of the starting line
<img width="950" alt="circuitracetrackperspectivestartlane" src="https://user-images.githubusercontent.com/15746225/40264725-aeb260b0-5af8-11e8-8203-a86fe12339d0.png">
