### ISSUE TITLE
Parallelize the path-planner

### ISSUE THREAD

**Issue by Oluwatoni** [uwrobotics/RobotRacing2018#9]
Offload the evaluation of paths to the GPU
The algorithm we use is trajectory rollout described [here](http://wiki.ros.org/base_local_planner).

**Acceptability Criteria**
Determine if it is worth it first: How much of the time spent path planning is actually spent evaluating multiple paths. If over 40% of our time is spent evaluating paths. It might be worth it.

Inputs
- list of paths

Outputs
- Highest ranking path

Use the CUDA library to complete this task

**Comment by AdrianMalaran** [comment]
- CUDA was installed on Friday, June 22 2018

**Comment by Oluwatoni** [comment]
Not a significant task as the path planner only uses up 5-7% of CPU in contrast with lane detection which uses 30-40% per camera
